import type { OpeningSubmission, Submission } from './story'

export const openingSubmissions: OpeningSubmission[] = [
  {
    id: 'opening-submission-1',
    queueNumber: 1,
    authorName: 'kruque',
    text: 'Lodowa planeta o słabej grawitacji. Głębokie rozpadliny wśród ostrych szpicy sięgających nieba. Ciskane wichurą fragmenty zamarzniętych skał uniemożliwiają transport lotniczy. Między bazami fundującymi kolonię podróżuje się w ogromnych maszynach kroczących. Uciążliwe lodowe pająki nie boją się wciskać w każdą dostępną szczelinę.',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-2',
    queueNumber: 1,
    authorName: 'Green',
    text: 'Broń obcych zabiła nasz układ nerwowy ale Fundacja stworzyła biomechowe powłoki, teraz my jesteśmy bronią. Zwykli ludzie boją się nas, nie rozumieją, że chodzi o ich przyszłość. Wytropimy agentów wroga, silniejsi polecimy ku gwiazdom pomścić Terrę. Ofiary są konieczne by pokój zapanował w układzie.',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-3',
    queueNumber: 1,
    authorName: 'Waldi',
    text: '40 lat temu ludzie zniknęli. Została zdziczała globalna sieć - miliony serwerów zasiedlonych przez najróżniejsze programy. Przemierzają ją fantomy - echa świadomości pracowników Fundacji - skazane na wieczną ucieczkę przed oszalałymi antywirusami i protokołami terminacyjnymi. Łowcy śledzą ofiary po nadpisanych "logach strachu".',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-4',
    queueNumber: 1,
    authorName: 'Kubulozaurus',
    text: 'Ludzie nie boją się sięgnąć gwiazd. Nie mają wyjścia. Kulani dokonali szybkiej inwazji dzięki zaawansowanej technologii. Po ostatnich aresztowaniach przywódców rebeliantów, ruch oporu, zwany Fundacją właściwie nie istnieje. Ludzcy żołnierze, dzięki łatwej adaptacji do warunków klimatycznych wchodzą w skład Korpusu Ekspedycyjnego.',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-5',
    queueNumber: 1,
    authorName: 'Kubulozaurus',
    text: 'Jesteśmy dzielną załogą Szczura nr 16. Pracuje i żyje nas w tym ogromnym biomechanicznym gryzoniu 300 ludzi. Chodzimy nim po Nieskończonym Labiryncie w Fundacji Rozwoju. Szukamy żywności i zasobów, by wrócić z nimi do Gniazda. To metropolia pośrodku Labiryntu, baza dla setek Szczurów takich jak nasz. Nie bój się Kota, to tylko mit.',
    status: 'winner',
  },
  {
    id: 'opening-submission-6',
    queueNumber: 1,
    authorName: 'Horrax',
    text: 'Ciało, a wraz z nim mózg, zużywa się, ale SEN oraz mechanizm przebudzenia funkcyjnego (MPF) pozwalają, by Eminentni służyli społeczeństwu dłużej. Wybudzenie następuje wyłącznie wtedy, gdy system uzna czynnik ludzki za niezbędny. Właśnie zbudzono troje śledczych. Pewno nie później niż za trzy dni wybudzony zostanie sędzia.',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-7',
    queueNumber: 1,
    authorName: 'aerte',
    text: 'Replikator na statku spisał się bezbłędnie. Patrząc na obraz z kamer wyglądam i poruszam się dokładnie tak jak na materiałach przesłanych przez Fundację. Teraz zadanie jest banalnie proste, wystarczy polecieć na tę błękitną planetę, wtopić się w tłum i znaleźć kogoś kto nie zwieje na propozycję współpracy z naszymi kadrami.',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-8',
    queueNumber: 1,
    authorName: 'Kantor',
    text: 'Rok 2050. Odkryto Przejście Chronodynamiczne, labirynt, nieskończoną sieć korytarzy prowadzących do różnych miejsc i czasów. Jedne olśniewają kryształowym pięknem, inne wchłaniają materię. Nie bój się, Chronokartografie. Idź i zmapuj Tunele Temporalne pod spiralnym zejściem, a Fundacja zadba, by pamięć o tobie przetrwała.',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-9',
    queueNumber: 1,
    authorName: 'Rumid',
    text: 'Odkrycie kwantów psionicznych stawia ludzkość o krok od rozwiązania Paradoksu Fermiego. Wiemy już, że istoty świadome pozostawiają po sobie widmo własnej psyche, jakby próżnia odmawiała o nich zapomnieć. Skrybowie Fundacji Kardaszowa zostają wysłani do zbadania Epitafium: największego odkrytego skupiska wspomnień obcej cywilizacji.',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-10',
    queueNumber: 1,
    authorName: 'efi-efi',
    text: 'Wtedy starsze wersje nas pojawiały się i świat pogrążył się w chaosie. Porządek zaprowadził kościół Kronosa. Gdy w pełni ukształtuje się przysadka, to tworzy się checkpoint, do którego się wróci, gdy dozna się uczucia zawodu. Kościół uczy panowania nad tym uczuciem i wymaga, by po powrocie oddać się w jego ręce. Walczmy o wolność.',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-11',
    queueNumber: 1,
    authorName: 'Pieczar',
    text: 'Znany świat jest otoczony pulsującą zasłoną, falującym zwierciadłem. Natura tegoż jest niezrozumiała dla większości, a zbliżanie się doń jest zakazane. Przestrzegania tejże zasady pilnują postaci odziane w tkaninę wyglądającą jak sam kosmos. Nikt nie wie, gdzie znikają Ci, którzy próbują łamać zakaz. Ciekawość wśród młodych rośnie.',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-12',
    queueNumber: 1,
    authorName: 'autor niepodany',
    text: 'Czas. Ten Który Idzie Do Przodu. A co jeśli można mu się postawić? Wielka Galaktyczna Zbiórka, by dokonać tylko tego jednego. Pokonać go. Ziemię mało kto już pamięta. Gdyby można było tam wrócić? Czy strach i postęp to jedyne co nas powstrzymuje? TimeTech ma już odpowiedź. I ma też pomysł, na to co można zmienić w naszej historii.',
    status: 'unchosen-option',
  },
]

export const roundSubmissions: Submission[] = [
  {
    id: 'submission-2-1',
    roundId: 'round-2',
    optionId: 'option-2-3',
    authorName: 'Ifryt',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: '– Kapitanie, jest otwór! Przechodzę. – Raportuj! – Droga do Gniazda ma ślady pazurów. Jest też grota. – Dziwne. Nie ma jej na mapie. – Wejście zarosło pulsobłoną. Tętni. Grota schodzi w dół. – Wracaj! Labirynt nie ma dróg w dół. Cyk. Cyk, cyk. Cykanie językiem. – Rozładuj jajo… – szepnął Nezumi tuż za mną. Ale przecież został w Szczurze!',
  },
  {
    id: 'submission-2-2',
    roundId: 'round-2',
    optionId: 'option-2-1',
    authorName: 'Rumid',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: '„Nie spodziewałem się tego po tobie!” Kapitan nagle stał się agresywny. „Tchórzysz? Raz dwa wykonaj rozkaz!” Skąd to dziwne zachowanie? Czy rozpoznał granatowy materiał? Zanim zdążysz odpowiedzieć, gdzieś w głębi Szczura słychać głośny łomot. Kolejne lampki na pulpicie zapalają się na czerwono. Szczur zaczyna się trząść. I piszczy.',
  },
  {
    id: 'submission-2-3',
    roundId: 'round-2',
    optionId: 'option-2-3',
    authorName: 'kruque',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Nezumi początkowo się sprzeciwia, ale w trakcie dyskusji ulega. Pot spływa mi po twarzy, a usta wyschły. Idziesz sama. Widzisz ślady walki. Zginęli tu Wasi. W oddali widzisz małą dziewczynkę. Ona Ciebie nie. Zaczynasz się pocić. Masz suche usta. Słyszysz w głowie „Oni... zabrali mi siostrę... wiesz gdzie ona jest?”',
  },
  {
    id: 'submission-2-4',
    roundId: 'round-2',
    optionId: 'option-2-2',
    authorName: 'efi-efi',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Kozak domykający śluzę jąkał się ze strachu, meldując powrót zwiadu. Kiza uspokoiła oddech. Obiekt — trójkątną płachtę z pękniętym stelażem — należało zbadać w warsztacie. Sapiąc, pchała wózek do poziomu Podbrzusza. Drzwi rupieciarni stały otworem. Po inż. Myszkinie pozostał tylko fartuch. Po jaju — skorupa w kałuży zielonej mazi.',
  },
  {
    id: 'submission-2-5',
    roundId: 'round-2',
    optionId: 'option-2-2',
    authorName: 'ludwik',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Gdy mech-ramię podnosi kolejny głaz, Amir, jeden z Kozaków, zagaja Kizę. „Widziałaś kiedyś Kota? Ponoć Nezumi to jedyny ocalały ze Szczura 7...” Zamilkł, gdy zmierzyła go wzrokiem. „Skupcie się na gruzowisku, podporuczniku”. Strzępy zaczęły powiewać niczym flaga. Kiza uśmiechnęła się, gdy nagle rozległo się przeciągłe mruczenie.',
  },
  {
    id: 'submission-2-6',
    roundId: 'round-2',
    optionId: 'option-2-1',
    authorName: 'Horrax',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Z trudem przekonujesz upartego kapitana. Co wam po ładunku, który ugrzęźnie gdzieś w gruzach? — Zwrot na lewo i cała naprzód! — słychać rozkaz, ale pospieszany jakąś niewidzialną siłą przez całą drogę powrotną Szczur napina się i nie współpracuje. Zupełnie jakby się bał. — Cholera, awaria?! — klniesz, szarpiąc bezskutecznie ster.',
  },
  {
    id: 'submission-2-7',
    roundId: 'round-2',
    optionId: 'option-2-2',
    authorName: 'Kantor',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Odrzucacie kilka głazów na bok i waszym oczom ukazuje się plątanina granatowej liny. Jeden z jej końców utknął gdzieś pod rumowiskiem, ale druga część zdaje się prowadzić dalej, w czeluści niezbadanego korytarza Labiryntu. Nagle lina napręża się, mało nie wywracając jednego z Kozaków. Reszta patrzy na ciebie czekając na rozkaz.',
  },
  {
    id: 'submission-2-8',
    roundId: 'round-2',
    optionId: 'option-2-2',
    authorName: 'Green',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'winner',
    text: 'Kleszcze mech-ramienia zgrzytają na głazach. Co chwilę przecieracie wizjery z osiadającego, lepkiego pyłu. W końcu praca ustaje. Cisza. Kozak z miotaczem ognia nie potrafi opanować drżenia rąk. Klekot jego broni niesie się po korytarzu słabym echem. Przechodzi cię zimny dreszcz. Przed wami leży rozszarpany sztandar Szczura 13.',
  },
  {
    id: 'submission-2-9',
    roundId: 'round-2',
    optionId: 'option-2-1',
    authorName: 'Waldi',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Z wysiłkiem zawróciliście Szczura do odnogi korytarza. Cztery dni do Gniazda. Szczur nagle przestał się śpieszyć. Trzy dni. Tral znalazł drzwi do kontenera otwarte. Nigdzie nie ma wartowników. Dwa dni. Z Kapitana została tylko jego kurtka. Coś cyka w bocznych korytarzach. Jeden dzień. Szczur się zatrzymał. Została was dwudziestka.',
  },
  {
    id: 'submission-2-10',
    roundId: 'round-2',
    optionId: 'option-2-3',
    authorName: 'Kubulozaurus.Rex',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Ślady pazurów zaprowadziły cię do wielkiej pokrytej fluorescencyjnymi grzybami pieczary. Ze środka dobiegają odgłosy. Specyficzne pomrukiwanie Kota oraz coś co brzmi jak piski i mlaskania. Korzystając ze skafandra wspinasz się na sufit i serce ci bije szybciej gdy orientujesz się czego jesteś świadkiem. Narada potwora z Kretomułem!',
  },
  {
    id: 'submission-2-11',
    roundId: 'round-2',
    optionId: 'option-2-2',
    authorName: 'aerte',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Idziesz przez gruzowisko w ostrym blasku szczurzego reflektora. Tu! Zaczynamy! Mocne kierunkowe światło wydobywa każdy detal terenu i sprawia, że pracujące mech-ramię i trzy sylwetki Kozaków tworzą groteskowy teatr cieni na ścianie korytarza. Mamy to! Drżącym głosem mówisz do radia: „Nezumi? To granatowe... to wielka mysz-zabawka”.',
  },
  {
    id: 'submission-2-12',
    roundId: 'round-2',
    optionId: 'option-2-2',
    authorName: 'autor niepodany',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Mech-ramię sięga po materiał, ale to coś większego. Kłębek granatowo połyskujących lin. Czy to włosy? Oplata kilka ludzkich czaszek i skorupy jaj. Między skałami, skąd wyciągnęliśmy kłębek, widać prześwit. Wtem zza pleców dobiega basowy pomruk. W ciemności za szczurem widać dwie fioletowe kule. Oczy? A my, kurwa, mamy miotacz.',
  },
  {
    id: 'submission-3-1',
    roundId: 'round-3',
    optionId: 'option-3-2',
    authorName: 'Baksu',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'winner',
    text: 'Kozacy natychmiast ruszają do dalszej pracy. Niedługo potem spod zwałowiska wyciągacie dowody katastrofy: powłokę szczurzego ogona, hełm z wyrytą liczbą 13, poszarpany skafander. Poruszył się! Odkopujecie rannego Kozaka. Łapczywie pije wodę z bukłaka, który mu podstawiasz do ust. Jego wargi wypowiadają nieme „Jajo. To pułapka”.',
  },
  {
    id: 'submission-3-2',
    roundId: 'round-3',
    optionId: 'option-3-2',
    authorName: 'Green',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Wszyscy zaczynają kopać, nawet gołymi rękami. Odkrywacie jednego z załogantów 13stki. Ledwo oddycha. Otwiera oczy w których widzicie serowo żółte tęczówki. Widząc Was zaciska mocniej metalowe szpony, które trzyma w ręce i... wbija je sobie pod brodę. Końcówki wybijają trzy otwory w górze czaszki. Krew obryzguje twoje policzki.',
  },
  {
    id: 'submission-3-3',
    roundId: 'round-3',
    optionId: 'option-3-2',
    authorName: 'kruque',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Ale że trzynastka? - Skrzeczący głos Nezumiego ledwo przebija się przez hałas mech-ramienia. - Stary Kiryło to szczwany szczur. Nie dałby się tak łatwo... - lawina skał ostatecznie odsłania burtę Szczura 13. Jest rozpruta. Od wewnątrz. Kapitan nie kończy wywodu mimo otwartego łącza. Kapitanie? Nezumi!? Mech-ramię nagle zastyga.',
  },
  {
    id: 'submission-3-4',
    roundId: 'round-3',
    optionId: 'option-3-3',
    authorName: 'Kubulozaurus.Rex',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'PAJ-N3 - napisano na skafandrze. Zaiste, dłonie same trzymały się sufitu. Za zawaliskiem cicho, odległy chrobot mecha-ręki. Widok - istny horror: strzępki sierści, kałuże hydraulicznej posoki ze szczurzych arterii. Urwana ręka, z naszywką pechowego załoganta. Wśród tego - złamany, koci wąs. Z ciemności dobiegło żałosne miauknięcie.',
  },
  {
    id: 'submission-3-5',
    roundId: 'round-3',
    optionId: 'option-3-2',
    authorName: 'efi-efi',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Mech-ramię odrzuca na bok kolejne głazy. Jeden z Kozaków melduje: „Coś mam!”. Migająca na czerwono kontrolka. „To właz awaryjny. Oznaczenie J-7, środek lewego boku”. Otwieracie go siłą. Trudno tu się poruszać: Szczur leży na boku, a większość korytarzy jest zmiażdżona. Znajdujecie tylko kolejne zwłoki... Wtem cichy głos: „Pomocy!”.',
  },
  {
    id: 'submission-3-6',
    roundId: 'round-3',
    optionId: 'option-3-2',
    authorName: 'Ifryt',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Szczur jest rozbebeszony. Mieszanina kabli i żył wije się z trzewi. Trzeba nieco siłować się z posadzką, lepką od płynów technicznych i ustrojowych. Usłyszawszy cichy jęk lufa miotacza wycelowała w stronę źródła dźwięku. Kiza wstrzymała towarzysza, nie wierząc własnym oczom. Pokrwawiona opaska kapitańska... i ta twarz, jak Nezumi.',
  },
  {
    id: 'submission-3-7',
    roundId: 'round-3',
    optionId: 'option-3-1',
    authorName: 'aerte',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Wśród głazów dostrzegasz obły kształt. Czyżby kolejne jajo, takie jak znaleźliście niedawno? Tyle że to przed chwilą zostało potraktowane miotaczem płomieni przez nerwowego Kozaka. A teraz na powierzchni jaja zaczynają pojawiać się rysy i coś ewidentnie rusza się w środku. Posiłki ze Szczura nie dotrą do was wystarczająco szybko.',
  },
  {
    id: 'submission-3-8',
    roundId: 'round-3',
    optionId: 'option-3-3',
    authorName: 'ludwik',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Przywierając do ściany suniesz wzdłuż zadrapania. W dole ogon Szczura 13 wystaje ze zwaliska. Przeciskasz się przez szczelinę. Pole siłowe skafandra jarzy się błękitem pod naporem skał. Blask na chwilę odsłania obszerną salę. Pod sufitem wiszą ciała. Starannie rozwieszone na sznurkach. Kołyszą się niczym zabawkowe wahadła.',
  },
  {
    id: 'submission-3-9',
    roundId: 'round-3',
    optionId: '',
    authorName: 'Erich (Vargur)',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Remiego znajdujecie w stanie krytycznym, pośród makabrycznie rozciągniętych ciał reszty załogi pechowej Trzynastki. Ruszacie dalej, nerwowi i niemal pewni nadchodzących kłopotów. Ślady pazurów są teraz częstsze. „Po nitce do kłębka” – mówi wydrapany na bramie napis w oddalonym o godzinę od Gniazda - opuszczonym punkcie kontrolnym.',
  },
  {
    id: 'submission-3-10',
    roundId: 'round-3',
    optionId: 'option-3-2',
    authorName: 'Kantor',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: '– Kapitanie, to 13. – Kopcie! Wszystkie krety, pełna moc! Siłociąg skafandra ruszył głaz, tworząc szczelinę. Zerknęłam. Nic. Czerń. Nie było labiryntu! Tylko ten dźwięk. Szept? Oddech? Zbliżał się. O kurwa! Ten gruz nie był przeszkodą. On nas chronił. – Nie kopcie! [W Szczurze] – Wyłączcie radio. – Ale, kapitanie... – To rozkaz!',
  },
  {
    id: 'submission-3-11',
    roundId: 'round-3',
    optionId: 'option-3-3',
    authorName: 'rumid',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Ostrożnie osuwasz się spod sufitu. Twoim oczom ukazuje się fragment wraku Szczura 13. Blachy jego pancerza są powyginane do zewnątrz, a porozrywane kable iskrzą się w ciemnym dymie. Pośród zgliszcz lśni skorupa wyklutego jaja. Twój wykrywacz ruchu zaczyna piszczeć, wskazując na koniec korytarza.',
  },
  {
    id: 'submission-3-12',
    roundId: 'round-3',
    optionId: '',
    authorName: 'autor niepodany',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Podnosisz z ziemi kawałek sierści. Strasznie śmierdzi sokami trawiennymi. Jest duży, zbity, wilgotny i... jeszcze ciepły. Powrót! Wracajcie szybko! - krzyczysz przez laryngofon do pozostawionych na miejscu rzezi kompanów. Nikt Ci nie odpowiada. Za to z ciemności, powoli, dobiega do ciebie gardłowe pomrukiwanie.',
  },
]
