import type { OpeningSubmission, Submission } from './story'

export const openingSubmissions: OpeningSubmission[] = [
  {
    id: 'opening-submission-1',
    queueNumber: 1,
    authorName: 'Ifryt',
    text: 'Lodowa planeta o słabej grawitacji. Głębokie rozpadliny wśród ostrych szpicy sięgających nieba. Ciskane wichurą fragmenty zamarzniętych skał uniemożliwiają transport lotniczy. Między bazami fundującymi kolonię podróżuje się w ogromnych maszynach kroczących. Uciążliwe lodowe pająki nie boją się wciskać w każdą dostępną szczelinę.',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-2',
    queueNumber: 1,
    authorName: 'kruque',
    text: 'Broń obcych zabiła nasz układ nerwowy ale Fundacja stworzyła biomechowe powłoki, teraz my jesteśmy bronią. Zwykli ludzie boją się nas, nie rozumieją, że chodzi o ich przyszłość. Wytropimy agentów wroga, silniejsi polecimy ku gwiazdom pomścić Terrę. Ofiary są konieczne by pokój zapanował w układzie.',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-3',
    queueNumber: 1,
    authorName: 'Green',
    text: '40 lat temu ludzie zniknęli. Została zdziczała globalna sieć - miliony serwerów zasiedlonych przez najróżniejsze programy. Przemierzają ją fantomy - echa świadomości pracowników Fundacji - skazane na wieczną ucieczkę przed oszalałymi antywirusami i protokołami terminacyjnymi. Łowcy śledzą ofiary po nadpisanych "logach strachu".',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-4',
    queueNumber: 1,
    authorName: 'Waldi',
    text: 'Ludzie nie boją się sięgnąć gwiazd. Nie mają wyjścia. Kulani dokonali szybkiej inwazji dzięki zaawansowanej technologii. Po ostatnich aresztowaniach przywódców rebeliantów, ruch oporu, zwany Fundacją właściwie nie istnieje. Ludzcy żołnierze, dzięki łatwej adaptacji do warunków klimatycznych wchodzą w skład Korpusu Ekspedycyjnego.',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-5',
    queueNumber: 1,
    authorName: 'Kubulozaurus.Rex',
    text: 'Jesteśmy dzielną załogą Szczura nr 16. Pracuje i żyje nas w tym ogromnym biomechanicznym gryzoniu 300 ludzi. Chodzimy nim po Nieskończonym Labiryncie w Fundacji Rozwoju. Szukamy żywności i zasobów, by wrócić z nimi do Gniazda. To metropolia pośrodku Labiryntu, baza dla setek Szczurów takich jak nasz. Nie bój się Kota, to tylko mit.',
    status: 'winner',
  },
  {
    id: 'opening-submission-6',
    queueNumber: 1,
    authorName: 'ludwik',
    text: 'Ciało, a wraz z nim mózg, zużywa się, ale SEN oraz mechanizm przebudzenia funkcyjnego (MPF) pozwalają, by Eminentni służyli społeczeństwu dłużej. Wybudzenie następuje wyłącznie wtedy, gdy system uzna czynnik ludzki za niezbędny. Właśnie zbudzono troje śledczych. Pewno nie później niż za trzy dni wybudzony zostanie sędzia.',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-7',
    queueNumber: 1,
    authorName: 'Horrax',
    text: 'Replikator na statku spisał się bezbłędnie. Patrząc na obraz z kamer wyglądam i poruszam się dokładnie tak jak na materiałach przesłanych przez Fundację. Teraz zadanie jest banalnie proste, wystarczy polecieć na tę błękitną planetę, wtopić się w tłum i znaleźć kogoś kto nie zwieje na propozycję współpracy z naszymi kadrami.',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-8',
    queueNumber: 1,
    authorName: 'aerte',
    text: 'Rok 2050. Odkryto Przejście Chronodynamiczne, labirynt, nieskończoną sieć korytarzy prowadzących do różnych miejsc i czasów. Jedne olśniewają kryształowym pięknem, inne wchłaniają materię. Nie bój się, Chronokartografie. Idź i zmapuj Tunele Temporalne pod spiralnym zejściem, a Fundacja zadba, by pamięć o tobie przetrwała.',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-9',
    queueNumber: 1,
    authorName: 'Kantor',
    text: 'Odkrycie kwantów psionicznych stawia ludzkość o krok od rozwiązania Paradoksu Fermiego. Wiemy już, że istoty świadome pozostawiają po sobie widmo własnej psyche, jakby próżnia odmawiała o nich zapomnieć. Skrybowie Fundacji Kardaszowa zostają wysłani do zbadania Epitafium: największego odkrytego skupiska wspomnień obcej cywilizacji.',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-10',
    queueNumber: 1,
    authorName: 'Rumid',
    text: 'Wtedy starsze wersje nas pojawiały się i świat pogrążył się w chaosie. Porządek zaprowadził kościół Kronosa. Gdy w pełni ukształtuje się przysadka, to tworzy się checkpoint, do którego się wróci, gdy dozna się uczucia zawodu. Kościół uczy panowania nad tym uczuciem i wymaga, by po powrocie oddać się w jego ręce. Walczmy o wolność.',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-11',
    queueNumber: 1,
    authorName: 'efi-efi',
    text: 'Znany świat jest otoczony pulsującą zasłoną, falującym zwierciadłem. Natura tegoż jest niezrozumiała dla większości, a zbliżanie się doń jest zakazane. Przestrzegania tejże zasady pilnują postaci odziane w tkaninę wyglądającą jak sam kosmos. Nikt nie wie, gdzie znikają Ci, którzy próbują łamać zakaz. Ciekawość wśród młodych rośnie.',
    status: 'unchosen-option',
  },
  {
    id: 'opening-submission-12',
    queueNumber: 1,
    authorName: 'Pieczar',
    text: 'Czas. Ten Który Idzie Do Przodu. A co jeśli można mu się postawić? Wielka Galaktyczna Zbiórka, by dokonać tylko tego jednego. Pokonać go. Ziemię mało kto już pamięta. Gdyby można było tam wrócić? Czy strach i postęp to jedyne co nas powstrzymuje? TimeTech ma już odpowiedź. I ma też pomysł, na to co można zmienić w naszej historii.',
    status: 'unchosen-option',
  },
]

export const roundSubmissions: Submission[] = [
  {
    id: 'submission-2-1',
    roundId: 'round-2',
    optionId: 'option-2-3',
    authorName: 'Erich (Vargur)',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: '– Kapitanie, jest otwór! Przechodzę. – Raportuj! – Droga do Gniazda ma ślady pazurów. Jest też grota. – Dziwne. Nie ma jej na mapie. – Wejście zarosło pulsobłoną. Tętni. Grota schodzi w dół. – Wracaj! Labirynt nie ma dróg w dół. Cyk. Cyk, cyk. Cykanie językiem. – Rozładuj jajo… – szepnął Nezumi tuż za mną. Ale przecież został w Szczurze!',
  },
  {
    id: 'submission-2-2',
    roundId: 'round-2',
    optionId: 'option-2-1',
    authorName: 'Ifryt',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: '„Nie spodziewałem się tego po tobie!” Kapitan nagle stał się agresywny. „Tchórzysz? Raz dwa wykonaj rozkaz!” Skąd to dziwne zachowanie? Czy rozpoznał granatowy materiał? Zanim zdążysz odpowiedzieć, gdzieś w głębi Szczura słychać głośny łomot. Kolejne lampki na pulpicie zapalają się na czerwono. Szczur zaczyna się trząść. I piszczy.',
  },
  {
    id: 'submission-2-3',
    roundId: 'round-2',
    optionId: 'option-2-3',
    authorName: 'Rumid',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Nezumi początkowo się sprzeciwia, ale w trakcie dyskusji ulega. Pot spływa mi po twarzy, a usta wyschły. Idziesz sama. Widzisz ślady walki. Zginęli tu Wasi. W oddali widzisz małą dziewczynkę. Ona Ciebie nie. Zaczynasz się pocić. Masz suche usta. Słyszysz w głowie „Oni... zabrali mi siostrę... wiesz gdzie ona jest?”',
  },
  {
    id: 'submission-2-4',
    roundId: 'round-2',
    optionId: 'option-2-2',
    authorName: 'kruque',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Kozak domykający śluzę jąkał się ze strachu, meldując powrót zwiadu. Kiza uspokoiła oddech. Obiekt — trójkątną płachtę z pękniętym stelażem — należało zbadać w warsztacie. Sapiąc, pchała wózek do poziomu Podbrzusza. Drzwi rupieciarni stały otworem. Po inż. Myszkinie pozostał tylko fartuch. Po jaju — skorupa w kałuży zielonej mazi.',
  },
  {
    id: 'submission-2-5',
    roundId: 'round-2',
    optionId: 'option-2-2',
    authorName: 'efi-efi',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Gdy mech-ramię podnosi kolejny głaz, Amir, jeden z Kozaków, zagaja Kizę. „Widziałaś kiedyś Kota? Ponoć Nezumi to jedyny ocalały ze Szczura 7...” Zamilkł, gdy zmierzyła go wzrokiem. „Skupcie się na gruzowisku, podporuczniku”. Strzępy zaczęły powiewać niczym flaga. Kiza uśmiechnęła się, gdy nagle rozległo się przeciągłe mruczenie.',
  },
  {
    id: 'submission-2-6',
    roundId: 'round-2',
    optionId: 'option-2-1',
    authorName: 'ludwik',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Z trudem przekonujesz upartego kapitana. Co wam po ładunku, który ugrzęźnie gdzieś w gruzach? — Zwrot na lewo i cała naprzód! — słychać rozkaz, ale pospieszany jakąś niewidzialną siłą przez całą drogę powrotną Szczur napina się i nie współpracuje. Zupełnie jakby się bał. — Cholera, awaria?! — klniesz, szarpiąc bezskutecznie ster.',
  },
  {
    id: 'submission-2-7',
    roundId: 'round-2',
    optionId: 'option-2-2',
    authorName: 'Horrax',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Odrzucacie kilka głazów na bok i waszym oczom ukazuje się plątanina granatowej liny. Jeden z jej końców utknął gdzieś pod rumowiskiem, ale druga część zdaje się prowadzić dalej, w czeluści niezbadanego korytarza Labiryntu. Nagle lina napręża się, mało nie wywracając jednego z Kozaków. Reszta patrzy na ciebie czekając na rozkaz.',
  },
  {
    id: 'submission-2-8',
    roundId: 'round-2',
    optionId: 'option-2-2',
    authorName: 'Kantor',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'winner',
    text: 'Kleszcze mech-ramienia zgrzytają na głazach. Co chwilę przecieracie wizjery z osiadającego, lepkiego pyłu. W końcu praca ustaje. Cisza. Kozak z miotaczem ognia nie potrafi opanować drżenia rąk. Klekot jego broni niesie się po korytarzu słabym echem. Przechodzi cię zimny dreszcz. Przed wami leży rozszarpany sztandar Szczura 13.',
  },
  {
    id: 'submission-2-9',
    roundId: 'round-2',
    optionId: 'option-2-1',
    authorName: 'Green',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Z wysiłkiem zawróciliście Szczura do odnogi korytarza. Cztery dni do Gniazda. Szczur nagle przestał się śpieszyć. Trzy dni. Tral znalazł drzwi do kontenera otwarte. Nigdzie nie ma wartowników. Dwa dni. Z Kapitana została tylko jego kurtka. Coś cyka w bocznych korytarzach. Jeden dzień. Szczur się zatrzymał. Została was dwudziestka.',
  },
  {
    id: 'submission-2-10',
    roundId: 'round-2',
    optionId: 'option-2-3',
    authorName: 'Waldi',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Ślady pazurów zaprowadziły cię do wielkiej pokrytej fluorescencyjnymi grzybami pieczary. Ze środka dobiegają odgłosy. Specyficzne pomrukiwanie Kota oraz coś co brzmi jak piski i mlaskania. Korzystając ze skafandra wspinasz się na sufit i serce ci bije szybciej gdy orientujesz się czego jesteś świadkiem. Narada potwora z Kretomułem!',
  },
  {
    id: 'submission-2-11',
    roundId: 'round-2',
    optionId: 'option-2-2',
    authorName: 'Kubulozaurus.Rex',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Idziesz przez gruzowisko w ostrym blasku szczurzego reflektora. Tu! Zaczynamy! Mocne kierunkowe światło wydobywa każdy detal terenu i sprawia, że pracujące mech-ramię i trzy sylwetki Kozaków tworzą groteskowy teatr cieni na ścianie korytarza. Mamy to! Drżącym głosem mówisz do radia: „Nezumi? To granatowe... to wielka mysz-zabawka”.',
  },
  {
    id: 'submission-2-12',
    roundId: 'round-2',
    optionId: 'option-2-2',
    authorName: 'aerte',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Mech-ramię sięga po materiał, ale to coś większego. Kłębek granatowo połyskujących lin. Czy to włosy? Oplata kilka ludzkich czaszek i skorupy jaj. Między skałami, skąd wyciągnęliśmy kłębek, widać prześwit. Wtem zza pleców dobiega basowy pomruk. W ciemności za szczurem widać dwie fioletowe kule. Oczy? A my, kurwa, mamy miotacz.',
  },
  {
    id: 'submission-3-1',
    roundId: 'round-3',
    optionId: 'option-3-2',
    authorName: 'Horrax',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'winner',
    text: 'Kozacy natychmiast ruszają do dalszej pracy. Niedługo potem spod zwałowiska wyciągacie dowody katastrofy: powłokę szczurzego ogona, hełm z wyrytą liczbą 13, poszarpany skafander. Poruszył się! Odkopujecie rannego Kozaka. Łapczywie pije wodę z bukłaka, który mu podstawiasz do ust. Jego wargi wypowiadają nieme „Jajo. To pułapka”.',
  },
  {
    id: 'submission-3-2',
    roundId: 'round-3',
    optionId: 'option-3-2',
    authorName: 'Baksu',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Wszyscy zaczynają kopać, nawet gołymi rękami. Odkrywacie jednego z załogantów 13stki. Ledwo oddycha. Otwiera oczy w których widzicie serowo żółte tęczówki. Widząc Was zaciska mocniej metalowe szpony, które trzyma w ręce i... wbija je sobie pod brodę. Końcówki wybijają trzy otwory w górze czaszki. Krew obryzguje twoje policzki.',
  },
  {
    id: 'submission-3-3',
    roundId: 'round-3',
    optionId: 'option-3-2',
    authorName: 'Green',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Ale że trzynastka? - Skrzeczący głos Nezumiego ledwo przebija się przez hałas mech-ramienia. - Stary Kiryło to szczwany szczur. Nie dałby się tak łatwo... - lawina skał ostatecznie odsłania burtę Szczura 13. Jest rozpruta. Od wewnątrz. Kapitan nie kończy wywodu mimo otwartego łącza. Kapitanie? Nezumi!? Mech-ramię nagle zastyga.',
  },
  {
    id: 'submission-3-4',
    roundId: 'round-3',
    optionId: 'option-3-3',
    authorName: 'kruque',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'PAJ-N3 - napisano na skafandrze. Zaiste, dłonie same trzymały się sufitu. Za zawaliskiem cicho, odległy chrobot mecha-ręki. Widok - istny horror: strzępki sierści, kałuże hydraulicznej posoki ze szczurzych arterii. Urwana ręka, z naszywką pechowego załoganta. Wśród tego - złamany, koci wąs. Z ciemności dobiegło żałosne miauknięcie.',
  },
  {
    id: 'submission-3-5',
    roundId: 'round-3',
    optionId: 'option-3-2',
    authorName: 'Kubulozaurus.Rex',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Mech-ramię odrzuca na bok kolejne głazy. Jeden z Kozaków melduje: „Coś mam!”. Migająca na czerwono kontrolka. „To właz awaryjny. Oznaczenie J-7, środek lewego boku”. Otwieracie go siłą. Trudno tu się poruszać: Szczur leży na boku, a większość korytarzy jest zmiażdżona. Znajdujecie tylko kolejne zwłoki... Wtem cichy głos: „Pomocy!”.',
  },
  {
    id: 'submission-3-6',
    roundId: 'round-3',
    optionId: 'option-3-2',
    authorName: 'efi-efi',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Szczur jest rozbebeszony. Mieszanina kabli i żył wije się z trzewi. Trzeba nieco siłować się z posadzką, lepką od płynów technicznych i ustrojowych. Usłyszawszy cichy jęk lufa miotacza wycelowała w stronę źródła dźwięku. Kiza wstrzymała towarzysza, nie wierząc własnym oczom. Pokrwawiona opaska kapitańska... i ta twarz, jak Nezumi.',
  },
  {
    id: 'submission-3-7',
    roundId: 'round-3',
    optionId: 'option-3-1',
    authorName: 'Ifryt',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Wśród głazów dostrzegasz obły kształt. Czyżby kolejne jajo, takie jak znaleźliście niedawno? Tyle że to przed chwilą zostało potraktowane miotaczem płomieni przez nerwowego Kozaka. A teraz na powierzchni jaja zaczynają pojawiać się rysy i coś ewidentnie rusza się w środku. Posiłki ze Szczura nie dotrą do was wystarczająco szybko.',
  },
  {
    id: 'submission-3-8',
    roundId: 'round-3',
    optionId: 'option-3-3',
    authorName: 'aerte',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Przywierając do ściany suniesz wzdłuż zadrapania. W dole ogon Szczura 13 wystaje ze zwaliska. Przeciskasz się przez szczelinę. Pole siłowe skafandra jarzy się błękitem pod naporem skał. Blask na chwilę odsłania obszerną salę. Pod sufitem wiszą ciała. Starannie rozwieszone na sznurkach. Kołyszą się niczym zabawkowe wahadła.',
  },
  {
    id: 'submission-3-9',
    roundId: 'round-3',
    optionId: 'option-3-1',
    authorName: 'ludwik',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Remiego znajdujecie w stanie krytycznym, pośród makabrycznie rozciągniętych ciał reszty załogi pechowej Trzynastki. Ruszacie dalej, nerwowi i niemal pewni nadchodzących kłopotów. Ślady pazurów są teraz częstsze. „Po nitce do kłębka” – mówi wydrapany na bramie napis w oddalonym o godzinę od Gniazda - opuszczonym punkcie kontrolnym.',
  },
  {
    id: 'submission-3-10',
    roundId: 'round-3',
    optionId: 'option-3-2',
    authorName: 'Erich [Vargur]',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: '– Kapitanie, to 13. – Kopcie! Wszystkie krety, pełna moc! Siłociąg skafandra ruszył głaz, tworząc szczelinę. Zerknęłam. Nic. Czerń. Nie było labiryntu! Tylko ten dźwięk. Szept? Oddech? Zbliżał się. O kurwa! Ten gruz nie był przeszkodą. On nas chronił. – Nie kopcie! [W Szczurze] – Wyłączcie radio. – Ale, kapitanie... – To rozkaz!',
  },
  {
    id: 'submission-3-11',
    roundId: 'round-3',
    optionId: 'option-3-3',
    authorName: 'Kantor',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Ostrożnie osuwasz się spod sufitu. Twoim oczom ukazuje się fragment wraku Szczura 13. Blachy jego pancerza są powyginane do zewnątrz, a porozrywane kable iskrzą się w ciemnym dymie. Pośród zgliszcz lśni skorupa wyklutego jaja. Twój wykrywacz ruchu zaczyna piszczeć, wskazując na koniec korytarza.',
  },
  {
    id: 'submission-3-12',
    roundId: 'round-3',
    optionId: 'option-3-1',
    authorName: 'rumid',
    submittedAt: '2020-08-02T22:00:00Z',
    status: 'unchosen-option',
    text: 'Podnosisz z ziemi kawałek sierści. Strasznie śmierdzi sokami trawiennymi. Jest duży, zbity, wilgotny i... jeszcze ciepły. Powrót! Wracajcie szybko! - krzyczysz przez laryngofon do pozostawionych na miejscu rzezi kompanów. Nikt Ci nie odpowiada. Za to z ciemności, powoli, dobiega do ciebie gardłowe pomrukiwanie.',
  },
  {
    id: 'submission-4-1',
    roundId: 'round-4',
    optionId: 'option-4-2',
    authorName: 'kruque',
    submittedAt: '2026-08-09T20:00:00Z',
    status: 'unchosen-option',
    text: 'Co u licha znaczy „trojańskie”? Biegnąc do ładowni, kminisz ostatnie słowa ocaleńca z 13-tki. Zaalarmowany przez radio inżynier Myszkin czeka z palnikiem. Łapiesz spektrometr, szybki skan — brak oznak aktywności. Znajdujesz jednak widoczny w podczerwieni symbol Щр-6 na dolnym fragmencie skorupy i wiesz już, kto zniósł trefne jajo.',
  },
  {
    id: 'submission-4-2',
    roundId: 'round-4',
    optionId: 'option-4-2',
    authorName: 'rumid',
    submittedAt: '2026-08-09T20:00:00Z',
    status: 'unchosen-option',
    text: 'Odseparowujesz nanoboty od części ciekłokrystalicznej. Bez niej jesteś w stanie podłączyć je do komputera i przeanalizować przebieg wydarzeń. Na podstawie ich trajektorii można wywnioskować, że były częścią jednostki bojowej. Znacznie mniejszej od szczurów, ale dużo szybszej. Szczur-13 musiał dać się zaskoczyć.',
  },
  {
    id: 'submission-4-3',
    roundId: 'round-4',
    optionId: 'option-4-1',
    authorName: 'Kubulozaurus.Rex',
    submittedAt: '2026-08-09T20:00:00Z',
    status: 'unchosen-option',
    text: '„To pułapka. WYRZUĆCIE JE! Von Henzelt, nasz doktor-inżynier, on je badał... To zaczęło wibrować. Coraz mocniej. Aż cały Szczur wibrował. Trząsł się od nosa do ogona. Von Henzelt powiedział, że ta wibracja to wiadomość, że drgania się przenoszą po labiryncie, bardzo daleko. Chciał zrozumieć... Wtedy COŚ odpowiedziało. Mruczeniem.”',
  },
  {
    id: 'submission-4-4',
    roundId: 'round-4',
    optionId: 'option-4-3',
    authorName: 'Kantor',
    submittedAt: '2026-08-09T20:00:00Z',
    status: 'unchosen-option',
    text: 'Gdy dobiegasz do Szesnastki, kadłub metalowego kolosa drży od walki w trzewiach. Ze środka dobiega wściekłe ujadanie karabinów przeplatane rykiem miotaczy ognia. Nagle stalową płytę przebija pięć gigantycznych pazurów, które prują pancerz statku jak papier. W wyszarpanej szczelinie błyszczy wielkie, pionowe ślepie.',
  },
  {
    id: 'submission-4-5',
    roundId: 'round-4',
    optionId: 'option-4-1',
    authorName: 'aerte',
    submittedAt: '2026-08-09T20:00:00Z',
    status: 'winner',
    text: '— To z jaja... Trysnęło tym, gdy pękło. To śluz rozpoczął jatkę - wydukał ocalony. Analizator wykrywa tego samego wirusa, co podczas epidemii na początku wyprawy. Jest też ludzkie DNA. Śluz zaatakuje układ nerwowy, jeśli wniknie w tkanki. — Nie dotykaj tego, Hiko! Za późno. Kozak konwulsyjnie wygina grzbiet i opada na cztery łapy.',
  },
  {
    id: 'submission-4-6',
    roundId: 'round-4',
    optionId: 'option-4-1',
    authorName: 'Green',
    submittedAt: '2026-08-09T20:00:00Z',
    status: 'unchosen-option',
    text: 'Kozak rzuca paranoiczne spojrzenia po ścianach korytarza. „To to wgryzło nam się w Szczura. Ssstraciliśmy kontrolę. Zaczął gryźć i obijać się o ściany.” Patrzy na rumowisko. „Spalcie to wszystko. WSZYSTKO.” Gdy mówisz mu o jaju, Kozak wyszarpuje ci z kabury szpon-pistolet i kończy swój żywot. Nagle wasz Szczur rusza w waszą stronę.',
  },
  {
    id: 'submission-4-7',
    roundId: 'round-4',
    optionId: 'option-4-2',
    authorName: 'Erich (Vargur)',
    submittedAt: '2026-08-09T20:00:00Z',
    status: 'unchosen-option',
    text: 'Kozak zaklął, gdy wirnik Laba chlusnął mu śluzem w oko. I zaczął widzieć. Sala. Pod sufitem wisi załoga 13, podłączona do Myślokradki! Kable pulsują. Zobaczyli mnie. Coś mówią. - Kozak podpiął się do Laba, zawył i padł. Z oka trysnęła krew. Ekran Laba iskrzył napisem „Nie ratujcie nas”. Bum! Bum! Dobiegło walenie spod gruzu.',
  },
  {
    id: 'submission-4-8',
    roundId: 'round-4',
    optionId: 'option-4-1',
    authorName: 'ludwik',
    submittedAt: '2026-08-09T20:00:00Z',
    status: 'unchosen-option',
    text: '– Jajo to przysmak – mówi, kiedy okrywasz go kocem i podajesz stymulant. – Czyj przysmak? – No, kota. Wyczuwa je z daleka. Chyba lubi takie tuż przed wykluciem, może podoba mu się ten śpiew. – Śpiew jaja?! – pytasz, dostrzegając w jego oczach obłęd. – No tak, nie słyszycie? Nuci, jakby kogoś wołało. Łowicie uchem cichą melodię.',
  },
  {
    id: 'submission-4-9',
    roundId: 'round-4',
    optionId: 'option-4-2',
    authorName: 'Horrax',
    submittedAt: '2026-08-09T20:00:00Z',
    status: 'unchosen-option',
    text: 'Kiedy aparatura zaczyna się trząść i piszczeć, Kozak z „13” łapie cię za nogawkę. „To co wyszło z Jaja... Było pokryte tym śluzem.” Czytasz wynik analizy i drapiesz się w głowę. Nic nie powinno przeżyć kontaktu z tak toksyczną substancją, ale pamiętasz badania w terenie: w Jaju coś pulsowało. Bez zwłoki wysyłasz raport do Nezumi.',
  },
  {
    id: 'submission-5-1',
    roundId: 'round-5',
    optionId: 'option-5-1',
    authorName: 'Erich (Vargur)',
    submittedAt: '2026-08-16T20:00:00Z',
    status: 'unchosen-option',
    text: 'Hiko wbija pazury głęboko w Twoje udo. Walisz go pięścią w pysk, tak że spada wprost na ocaleńca i nagle zastyga pod jego spojrzeniem. Ten szepcze: – Wezwij Królową. Hiko skomli, kuli się, zrywa do biegu i znika w tunelu, wyjąc. Z głębi Labiryntu odpowiadają kolejne wycia. Ocaleniec uśmiecha się paskudnie. – Mówiłem, że to pułapka.',
  },
  {
    id: 'submission-5-2',
    roundId: 'round-5',
    optionId: 'option-5-1',
    authorName: 'Horrax',
    submittedAt: '2026-08-16T20:00:00Z',
    status: 'unchosen-option',
    text: 'Próbujesz wyswobodzić się z żelaznego uścisku opętańca. Skąd on ma tyle siły? Nagle uścisk ustępuje - widzisz jak ktoś złapał Hiko w kleszcze mecha-ramienia. Teraz szamoce się bezbronnie w powietrzu. Zanosicie go do Szczura na dalsze badania. W drodze dostrzegasz rozprucie w swoim skafandrze, a pod nim pulsującą dziwnie ranę.',
  },
  {
    id: 'submission-5-3',
    roundId: 'round-5',
    optionId: 'option-5-3',
    authorName: 'Kubulozaurus.Rex',
    submittedAt: '2026-08-16T20:00:00Z',
    status: 'unchosen-option',
    text: 'Pajęczy zmysł! Skafander sam reaguje unikiem, a jego skorupa polimeryzuje z chrzęstem, stając się śliska jak jedwab. Atak Hiko chybia o włos i Kozak traci równowagę. Z niemożliwą zręcznością łapie cię drugą ręką, ale palce się ześlizgują. Leci w dół, w mrok rumowiska. Jego zwierzęcy ryk oddala się przez chwilę, po czym nagle urywa.',
  },
  {
    id: 'submission-5-4',
    roundId: 'round-5',
    optionId: 'option-5-2',
    authorName: 'kruque',
    submittedAt: '2026-08-16T20:00:00Z',
    status: 'unchosen-option',
    text: 'Chlast! Stalowa gródź odcina rękę jednego ze skażonych. Drzwi drżą pod ciosami rozpędzonych ciał. Ostrożnie podnosisz urwaną kończynę. W ambulatorium podgrzana palnikiem zepsuta krew miota się w próbówce. Testujesz Pafnuca — on też zdołał zbiec do Szczura. Zdrów! Ocierasz pot z czoła. Wtem wyje alarm: KOD 6! No bez jaj, to magazyn!',
  },
  {
    id: 'submission-5-5',
    roundId: 'round-5',
    optionId: 'option-5-3',
    authorName: 'ludwik',
    submittedAt: '2026-08-16T20:00:00Z',
    status: 'unchosen-option',
    text: 'W szamotaninie uderzacie o ścianę, która pęka z trzaskiem. Spadacie w ciemność. Strzelasz w ostatniej chwili, rozłupując czaszkę czemuś, co kiedyś było Hirem. Kombinezon ucierpiał, amortyzując upadek, a energii starcza jedynie, by utrzymać migotliwe światło latarki. Czy to korytarz jeszcze sprzed założenia Gniazda? Radio milczy.',
  },
  {
    id: 'submission-5-6',
    roundId: 'round-5',
    optionId: 'option-5-1',
    authorName: 'rumid',
    submittedAt: '2026-08-16T20:00:00Z',
    status: 'unchosen-option',
    text: 'Strzelasz w niego, za późno. Wgryzł się w nogę. Wiesz, co teraz. Widzisz po twarzach kozaków, że oni również. — To był zaszczyt — mówi jeden, mierząc w ciebie miotaczem. Cisza. Nagle coś słychać. Czworonożni biegną w waszym kierunku. Słyszysz strzały. Światło. — Obudziła się! W sali szpitalnej stoi Nezumi. — Jak to zrobiłaś?',
  },
  {
    id: 'submission-5-7',
    roundId: 'round-5',
    optionId: 'option-5-3',
    authorName: 'Baksu',
    submittedAt: '2026-08-16T20:00:00Z',
    status: 'unchosen-option',
    text: 'Opadacie 5 metrów w dół na gruzowisko po drugiej stronie. Hiko tnie pazurami po twoim kombinezonie, a on ledwo się trzyma. Udaje Ci się odepchnąć go nogami. Mierzysz z rękawicy... „przepraszam”. Hiko opada na kamienie z dziurą w czaszce. „Halo!”, w radiu tylko szum. Słyszysz przeskakujące iskry na kombinezonie i smród spalenizny.',
  },
  {
    id: 'submission-5-8',
    roundId: 'round-5',
    optionId: 'option-5-3',
    authorName: 'aerte',
    submittedAt: '2026-08-16T20:00:00Z',
    status: 'unchosen-option',
    text: 'Impet, z jakim rzucił się Hiko, odrywa was od ściany. Spadacie za gruzowisko w skośny szyb. Na dnie czujesz jego oddech. Wgryzłby się, gdyby nie pomruk, który go przywołał. Hiko pędzi przez sterylnie białą salę z rzędami jaj. Z każdego wychodzi wężyk podłączony do ludzkiego ciała z logiem Fundacji. Teraz wiesz, po co ich tatuowano.',
  },
  {
    id: 'submission-5-9',
    roundId: 'round-5',
    optionId: 'option-5-2',
    authorName: 'Green',
    submittedAt: '2026-08-16T20:00:00Z',
    status: 'winner',
    text: 'Ze zgrozą stajesz przed zamkniętą śluzą. Słyszysz w radiu Nezumiego. „Przykro mi. Chciałem wysłać kogoś innego.” Udający martwego kozak z 13 podrywa się do ucieczki. Zostaje rozszarpany. „To jajo. Jest warte wszystkiego. To ostatnia prosta. Wybacz.” Widzisz, jak za plecami odmieńcy zatrzymują się, patrząc na ciebie wyczekująco.',
  },
  {
    id: 'submission-5-10',
    roundId: 'round-5',
    optionId: 'option-5-1',
    authorName: 'Kantor',
    submittedAt: '2026-08-16T20:00:00Z',
    status: 'unchosen-option',
    text: 'Dzikie machnięcie łapskiem zrzuca cię za zawał. Buty orzą gruz, wzbijając pył. Latarka odkrywa wrak Trzynastki, usłany wyschniętymi, poskręcanymi trupami. Pamięć mięśniowa przejmuje kontrolę. Obrót, garda - Hiko ląduje na czterech łapach tuż przed tobą. Zmutowany Kozak szczerzy kły i napina grzbiet, gotując się do skoku.',
  },
  {
    id: 'submission-6-1',
    roundId: 'round-6',
    optionId: 'option-6-3',
    authorName: 'Horrax',
    submittedAt: '2026-08-24T20:00:00Z',
    status: 'unchosen-option',
    text: 'Bierzesz się w garść i obmyślasz plan: powiadomić o wszystkim Gniazdo. Kozacy porzucili trochę sprzętu, który może się przydać: butla z paliwem miotacza ognia pozwala odpalić turbo w twoim skafandrze! Ruszasz tunelem wyrytym przez węża. Idąc skrótem, po kilku godzinach trafiasz do Gniazda i zamierasz. Pusto. Ani jednego Szczura.',
  },
  {
    id: 'submission-6-2',
    roundId: 'round-6',
    optionId: 'option-6-2',
    authorName: 'aerte',
    submittedAt: '2026-08-24T20:00:00Z',
    status: 'unchosen-option',
    text: 'Pęd. Nie tylko ty uciekasz, odmieńcy również pierzchną. Wielonogi cień chwyta ciebie i kilku z nich. Długie ramię wrzuca was w bezkształtne cielsko. Lepkie i upstrzone tysiącem wici, które wdzierają się w kark i rdzeń. Czujesz obcą świadomość. – Jajo. Zaprowadź do Gniazda, a przeżyjesz. Myślisz o doku Szczura 16. Bestia rusza.',
  },
  {
    id: 'submission-6-3',
    roundId: 'round-6',
    optionId: 'option-6-3',
    authorName: 'Baksu',
    submittedAt: '2026-08-24T20:00:00Z',
    status: 'unchosen-option',
    text: 'Słyszysz syknięcie od strony gruzowiska. Zaraz za nim pojawia się kolejne i kolejne. Trzęsącą ręką włączasz latarkę na hełmie. Widok małych węży dookoła paraliżuje Cię. Wszystkie patrzą na ciebie. Ich syk łączy się w jedną melodię, a ty zaczynasz mimowolnie opadać na kolana. Jesteś jak w transie. Węże powoli wpełzają na ciebie.',
  },
  {
    id: 'submission-6-4',
    roundId: 'round-6',
    optionId: 'option-6-3',
    authorName: 'kruque',
    submittedAt: '2026-08-24T20:00:00Z',
    status: 'unchosen-option',
    text: 'Ledwie człapiesz. W mroku czas nie istnieje. Blask instrumentów kombinezonu i fosforyzujący mech umożliwiają nawigację. Przy życiu trzyma cię zlizywana ze ścian woda i powinność wobec gniazda. Resztką sił docierasz do zewnętrznej grodzi - nadzieja pryska jak bańka mydlana. Rozdarta stal, trupy, zgliszcza. Ślady pazurów. I koci wąs.',
  },
  {
    id: 'submission-6-5',
    roundId: 'round-6',
    optionId: 'option-6-1',
    authorName: 'Green',
    submittedAt: '2026-08-24T20:00:00Z',
    status: 'unchosen-option',
    text: 'Wpadasz do ładowni i turbo rzuca cię na rozerwane jajo. Dociera do ciebie, że brodzisz po kostki w śluzie. I nic ci nie jest. Jak w transie wychodzisz na zalane korytarze, mijając załogę skuloną w potwornych pozach. Mostek jest pusty. Czytasz komunikat na jedynym ekranie: "Poprowadź nas do raju." Czujesz na plecach czyjś oddech.',
  },
  {
    id: 'submission-6-6',
    roundId: 'round-6',
    optionId: 'option-6-1',
    authorName: 'Erich (Vargur)',
    submittedAt: '2026-08-24T20:00:00Z',
    status: 'unchosen-option',
    text: 'Wpadasz do ładowni. Jest jajo! Dotykasz. Skorupa mięknie i wciąga Cię. W gęstej mazi unoszą się ciała, połączone mackami z pulsującym jądrem. W środku rośnie postać. Puls i wzrost. I wiotczenie ciał. Ślurp! Martwe ciało odpada od macki na stos innych, a ta sunie do Ciebie. – Jeszcze jedno i się wyklujesz – słyszysz głos z zewnątrz.',
  },
  {
    id: 'submission-6-7',
    roundId: 'round-6',
    optionId: 'option-6-2',
    authorName: 'ludwik',
    submittedAt: '2026-08-24T20:00:00Z',
    status: 'winner',
    text: 'Pędzisz sufitem, próbując zmylić trop. Na kolejnym skrzyżowaniu wykręcasz gwałtownie i przewrotem lądujesz w cieniu bocznego korytarza. Czekasz. Czworonożne gnojki nabierają się, ale maszkara za nimi przystaje i węszy intensywnie. – Kici kici, skurwysynu – detonujesz minę, zwalając sufit na łeb potwora. Teraz tylko dogonić 16-tkę.',
  },
  {
    id: 'submission-6-8',
    roundId: 'round-6',
    optionId: 'option-6-3',
    authorName: 'Kubulozaurus.Rex',
    submittedAt: '2026-08-24T20:00:00Z',
    status: 'unchosen-option',
    text: 'Zostawiona sama w Labiryncie... radzisz sobie świetnie! Pochodzisz z osady dalekiej od Gniazda i jako młoda dziewczyna spędzałaś dni na wędrówkach, odkrywając niebezpieczeństwa i cuda Labiryntu. Wiesz, jak wyjąć jedzenie z pułapek, jak wpiąć się do węzłów energii, jak czytać szlaki. Po dwóch dniach docierasz do Stacji-Na-Rozstaju.',
  },
  {
    id: 'submission-6-9',
    roundId: 'round-6',
    optionId: 'option-6-1',
    authorName: 'Kantor',
    submittedAt: '2026-08-24T20:00:00Z',
    status: 'unchosen-option',
    text: 'Wypadasz na zalaną olejem kratę maszynowni. „Pierwsza oficer jest skażona! Strzelać bez ostrzeżenia!” - wyją megafony nad ciężkim rytmem tłoków. Dwaj usmoleni mechanicy unoszą klucze, gotowi do ciosu. Zdzierasz hełm, pokazując steraną, ale zdrową twarz. Odstępują. „Wyłączyć wszystkie silniki!” - rozkazujesz. „Nezumi nas sprzedał!”',
  },
  {
    id: 'submission-6-10',
    roundId: 'round-6',
    optionId: 'option-6-3',
    authorName: 'rumid',
    submittedAt: '2026-08-24T20:00:00Z',
    status: 'unchosen-option',
    text: 'Sprawdzasz, ile masz wody. Za mało. Widzisz tylko jedno wyjście z tej sytuacji, ale będzie wymagało złamania przysięgi załogantów. Jebać to. Zaczynasz burzyć ściany. Po zburzeniu trzeciej słyszysz głośny huk. Wyrwa w nieboskłonie emanuje jasnym światłem. Z tego światła wyłania się dwóch gigantów w białych kitlach.',
  },
  {
    id: 'submission-7-1',
    roundId: 'round-7',
    optionId: 'option-7-3',
    authorName: 'Kantor',
    submittedAt: '2026-08-31T20:00:00Z',
    status: 'winner',
    text: 'Padasz na pancerz dziobu. Wbijasz palce pod właz awaryjny. Prostujesz nogi i wspomagana ciągiem jetpacka wyrywasz stal z nitów. Wpadasz na mostek. Na huk wyłomu Nezumi unosi dymiący rewolwer znad martwego sternika i z obłędem w oczach mierzy w ciebie. Za jego plecami, w grubym przeszkleniu rosną wrota Gniazda. Maszyna nie wyhamuje.',
  },
  {
    id: 'submission-7-2',
    roundId: 'round-7',
    optionId: 'option-7-2',
    authorName: 'Horrax',
    submittedAt: '2026-08-31T20:00:00Z',
    status: 'unchosen-option',
    text: 'W ostatniej chwili skaczesz i chwytasz się ogona pędzącej Szesnastki. Cała biomaszyna sapie. Tuż zaraz nurkuje do nieznanej ci nory. Snop światła oświetla jaskinię, a tam widzisz coś niezwykłego: złomowisko popsutych Szczurów. Wszystkie związane są ogonami. Coś drga. „Jajo. Daj nam je.” — odbija się echem chór nieludzkich głosów.',
  },
  {
    id: 'submission-7-3',
    roundId: 'round-7',
    optionId: 'option-7-1',
    authorName: 'Erich (Vargur)',
    submittedAt: '2026-08-31T20:00:00Z',
    status: 'unchosen-option',
    text: 'Szczur mknie jak pocisk, ale zdążasz. Skok, klapa, magazyn i… Nezumi, mierzący do załogi: — To bunt! — Wyrzuć jajo! Ono steruje 16! Gnamy wprost do Gniazda! — To jedyna szansa na lek na X. — To źródło X! — X jest już w Gnieździe. Kiza, zamknij nas w ładowni! — Kiza, opróżnij ładownię! Szsztrzrz… Twoje radio odbiera sygnał Gniazda.',
  },
  {
    id: 'submission-7-4',
    roundId: 'round-7',
    optionId: 'option-7-1',
    authorName: 'Green',
    submittedAt: '2026-08-31T20:00:00Z',
    status: 'unchosen-option',
    text: 'Widzisz bramę Gniazda i stojącego przed nią Szczura. Z jego trzewi wychodzi Nezumi z mosiężnym kluczem. Z impetem powalasz go i żądasz wyjaśnień. Charczy w twoją stronę: „Czy nie rozumiesz? Żyjemy w mistyfikacji Fundacji! Jedyna droga to zrównać to z ziemią. Jesteś odporna jak ja. Otwórz bramę, a razem zbudujemy nowe Gniazdo!”',
  },
  {
    id: 'submission-7-5',
    roundId: 'round-7',
    optionId: 'option-7-1',
    authorName: 'Kubulozaurus.Rex',
    submittedAt: '2026-08-31T20:00:00Z',
    status: 'unchosen-option',
    text: 'Skaczesz. Uderzenie całym rozpędem o Szczura pozbawia cię tchu, ale skafander pomaga ci się utrzymać. Znajdujesz właz awaryjny, wbijasz kod, wchodzisz. W środku chaos; wyją wszystkie alarmy. Po chwili jesteś na mostku. Nezumi zdąża tylko chrapnąć „Ty?”, zanim umiera z twoim nożem w krtani. „Zmiana kursu! Musimy zniszczyć to gówno”.',
  },
  {
    id: 'submission-7-6',
    roundId: 'round-7',
    optionId: 'option-7-3',
    authorName: 'kruque',
    submittedAt: '2026-08-31T20:00:00Z',
    status: 'unchosen-option',
    text: 'Nazumi kierował 16-tką, omijając znane podejścia do Gniazda. Fundacyjny K0T na pewno został w tyle, jajo bezpieczne, obłożone lodem. Gdy naukowcy zbadają śluz, ekstrahują czynnik X i stworzą nową, odporną rasę, on zgarnie całą chwałę! Alarm! Intruz w wentylacji! Czy to możliwe, by wścibska Kiza przeżyła? Nazumi złapał za miotacz.',
  },
  {
    id: 'submission-7-7',
    roundId: 'round-7',
    optionId: 'option-7-2',
    authorName: 'ludwik',
    submittedAt: '2026-08-31T20:00:00Z',
    status: 'unchosen-option',
    text: 'Nezumiego doganiasz w bramie Gniazda. — Stój! — mówisz zdyszana. — Widzę, że już poznałaś kłamstwa Fundacji — mówi, zerkając na jetpack. — Elity tej metropolii pasą się na trudzie Kozaków, a Kot to mit, który zmusza nas do posłuszeństwa. — I co? Zabijesz ich? — cedzisz. — Tak, ale najpierw będą uciekać przed nami jak szczury...',
  },
  {
    id: 'submission-7-8',
    roundId: 'round-7',
    optionId: 'option-7-1',
    authorName: 'aerte',
    submittedAt: '2026-08-31T20:00:00Z',
    status: 'unchosen-option',
    text: 'Dogoniasz Szczura tuż przed Gniazdem, lądując mu na grzbiecie. Widzisz czarne sylwetki czyhające w cieniu. Załoga ich nie widzi. Wpinasz się w port. — Nezumi! Tu są Koty! — wrzeszczysz. Wrota Gniazda otwierają się. — Wiem! Jajo nas wybawi! Nowa rasa je pokona! — słyszysz, gdy Szczur wpada do hangaru. Wielka łapa rozpruwa wrota.',
  },
]
